using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace GeoRaschet
{
    internal class Data
    {
        public double inf;
        public bool f;
        public int size;

        /// <summary>Инициализация интерфейса класса <see cref="Data"/></summary>
        /// <autogeneratedoc />
        /// TODO Edit XML Comment Template for #ctor
        public Data()
        {
            inf = 0;
            f = false;
            size = 0;
        }
    }
}